### ISSUE TITLE
Incorporate a not-for-profit society to fundraise

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#75]
So that we can collect donations more easily I'm proposing that we form a not-for-profit society.

Ideally, this society should have as low an upkeep as possible and require similar commitments from our members as we did before incorporating.

This means:

1) allow for board activities (meetings, votes, directives, etc.) to take place asynchronously and online via a secure medium (Github, Google Docs, Gitter, etc.) whenever beneficial to the members involved
2) minimize work required to file taxes
3) minimize work required to renew the society each year

Feedback and thoughts are welcome!

# TODO
- [ ] draft bylaws
- [ ] select a society name ([spreadsheet](https://docs.google.com/spreadsheets/d/1D0u1MjqH4Ti5ZIW-pARcQYzr6LiSW3ZOrdQnIKiIFyw/edit?usp=sharing))
- [ ] do a NUANS search to prove our name is availability
- [ ] sign up board members
- [ ] complete [registration forms](https://www.servicealberta.ca/business-incorporation.cfm)
- [ ] send registration forms and fee to [Service Alberta Corporate Registry](http://www.servicealberta.ca/812.cfm)

**Comment by benzittlau** [comment]
Hey Mark, I'm happy to step in here if you need the spot, but also happy to let someone else take it if they're interested/passionate about being involved.  Let me know!

**Comment by abramhindle** [comment]
http://www.servicealberta.ca/716.cfm While Mark has read this anyone else interested should read it as well. The nice thing about exchangejs is regular meetings meaning that we can plunk an AGM at the start or end of any of our meetings and get quorum with no problem.

I don't know if we can avoid AGM rules.

Sample Bylaws http://www.servicealberta.ca/pdf/Forms/Society_Bylaws_re-entered_(2).pdf

*** Edit: 4. of the Sample Bylaws needs to be modified to include electronic forms of communication that you seek ***

What's written on paper and what's done in practice are different things. The org committee approach could be used to make the tasks of the president, VP, Secretary, and Treasurer  easier by accepting some of the responsibility. We'll need members at large to be executives as well.

The biggest responsibility is not actually Pres or VP it's treasurer as the filing of financials each year determines if the society continues to exist.

**Comment by MHerszak** [comment]
@abramhindle just a thought on your last paragraph. By "filing of financials" you mean fundraising?

**Comment by abramhindle** [comment]
Filing of financials is an annual annoyance whereby you report to the govt what your society's bank account looks like, what came in and what came out. It is somewhat detailed. Essentially all payments, purchases, earnings etc. must be reported. You don't pay tax on them as far I understand, but you can't be a pot of private money abused by a priveleged few. Fundraising would be reported in filing of financials.

**Comment by MarkBennett** [comment]
Hey everyone. I've gotten a few samples of bylaws now and will try to get together a draft of them that I can circulate by next week.

We'll also need to come up with a name we can incorporate under. Here's a [spreadsheet with name ideas](https://docs.google.com/spreadsheets/d/1D0u1MjqH4Ti5ZIW-pARcQYzr6LiSW3ZOrdQnIKiIFyw/edit?usp=sharing).

**Comment by MarkBennett** [comment]
In my research so far I've come up with a few questions I could use some feedback on.

## What is the purpose of the society?

In order to leave as much meetup business as possible unaffected by incorporating, and to allow us to allow other meetups to easily fundraise in the future, I'm proposing that the societies purpose is educate, connect and inspire the Edmonton developer community for facilitating the organisation of events of interest to the Edmonton developer community. The society could facilitate with fundraising, technical or organisational insight, and resource sharing between meetups. For example, the society could run the bank account used for fundraising and would manage filing with the government  for all the meetup using it, it could share the recording gear between meetups, and provide advice on things like the day to day running of meetups, and it could provide things like code of conduct templates, etc. The society wouldn't actually run the meetups themselves, though the meetups could be the clients of the society.

## Who are the members of the society?

Based on the mandate above, the members of the society would be any meetup organisers we assist as opposed to the actual people attending events. Anyone interested could still join the society, but people attending events don't need to and importantly don't even need to know anything about the society.

## Do we want to collect fees from members?

I'm of two minds about this right now and am trying to get some advice. One the one side, not having any fees sends the message that anyone interested can have their say and be part of the society. On the other hand having a fee provides a barrier to entry, and requires members to show they're invested in the society. Ideally, this would mean that only people that are serious about their commitment to the meetup would be involved which could make running things easier. Right now I'm leaning towards requiring a token amount like $5 that wouldn't prohibit many people but would still require some money on the table. It would also make expiring memberships more straight forward.

##  Is everyone ok with voting with github, sending meeting notice and communications via email, and hosting meeting online or by phone?

Being able to things online and asynchronously would certainly make my life easier. We'd need to figure out how this fits in with official society meetings, etc.

I'd want to be clear that we'd still need to hold an AGM once a year (probably at the June Exchange.js meetup) and therefore in person versions of these would all exist. We'd just be clear that they were equivalent to their electronic counterparts.

##  Are we all ok with voting on board business via a GitHub issue setup for that purpose? What kind of notice and time period would people require to consider a vote fair and binding?

I like the idea of using GitHub and the reactions there to vote on things as we can have a good discussion and keep records using the comments. Thoughts?

##  Do we want to require a minimum age of 18? Why or why not?

I don't ​know of a good reason to require this, but advice would be welcome.



I'm sure I'll have more questions and will continue to share them here. I've got a few good bylaws now that I can use as templates for ours.

Thanks!

**Comment by abramhindle** [comment]
I wouldn't worry too much about the meta. But I think you're right. This is a lot of work and if the structure can be used to say fund another meetup, or allow funding of that meetup then so be it. Having the exec grant a budget or something to another meetup is in the power of the basic society form bylaws. I suggest avoid Javascript too much in the society description and whatnot but don't over think or overreach.

In my opinion from the sample bylaw I think you want to have fee for membership but nothing precludes events whereby the board agrees to grant membership. So we can make free members if the board agrees. This doesn't have to be in the actual bylaws.

Don't do too much. Don't put too much into bylaws. Keep to your plan of enabling electronic communication. Do not say github anywhere in the document --- say society issue tracker, we can change that issue tracker as need be.

For electronic communication it's all written as long as intent is clear I don't think you have to be overly formal. Maybe specify that votes have a time limit specified by the description of the topic being voted on.

Also think of adversarial actions, what could a small group do to disrupt your society. What can you do stop them but also be democratically fair. There's probably very little we could write down.

**Comment by MHerszak** [comment]
I like to pay a fee.

I am okay with electronic attendance for specific topics regarding the society.

I am kind of not okay to drift away from JS due to the vast amount of information in this field.

I also don't understand why this society should fund other meetups. I am not opposed I just don't understand it. If their is a valid reason I am all in.

**Comment by MarkBennett** [comment]
@abramhindle 

> I wouldn't worry too much about the meta. But I think you're right. This is a lot of work and if the structure can be used to say fund another meetup, or allow funding of that meetup then so be it. Having the exec grant a budget or something to another meetup is in the power of the basic society form bylaws. I suggest avoid Javascript too much in the society description and whatnot but don't over think or overreach.

Agreed. I'd like to bootstrap with Exchange.js for now, then evaluate supporting other meetups in the future. Leaving specific mentions of JS out of it seems to make sense.

> In my opinion from the sample bylaw I think you want to have fee for membership but nothing precludes events whereby the board agrees to grant membership. So we can make free members if the board agrees. This doesn't have to be in the actual bylaws.

Ok. Let's try it with a fee and see. I've got a sample bylaw with a good section on honorary members at the boards discretion. I'll cut and paste that in and go from there.
 
> Don't do too much. Don't put too much into bylaws. Keep to your plan of enabling electronic communication. Do not say github anywhere in the document --- say society issue tracker, we can change that issue tracker as need be.

Agreed about not getting too heavy or mentioning specific tools. We can focus on the exact wording once I've got the draft done.
 
> For electronic communication it's all written as long as intent is clear I don't think you have to be overly formal. Maybe specify that votes have a time limit specified by the description of the topic being voted on.

Some bylwas seem very specific about voting, others seem less so. I'm inclined to leave more to the boards judgement to begin with, then formalize things if we need later once we know how things work best.

> Also think of adversarial actions, what could a small group do to disrupt your society. What can you do stop them but also be democratically fair. There's probably very little we could write down.

Good point. Luckily I married a good lawyer who might be able to help with this. ;)

**Comment by MarkBennett** [comment]
@MHerszak 

> I like to pay a fee.
> 
> I am okay with electronic attendance for specific topics regarding the society.
> 
> I am kind of not okay to drift away from JS due to the vast amount of information in this field.

This is my second long term meetup I've organized (previously I ran YEGrb for 3-4 years or so.) My goal with this society is to directly benefit Excahnge.js, but also recognize that there's a lot we'll be doing which other meetups could benefit from in the future.  The organizers of those meetups might also be doing work that would benefit us. For example, I know some of the other meetups have started doing streaming setups, etc. Initially, we'd want to bootstrap with just Exchange.js, but then evaluate bringing other meetups on board.

On another note, I know over time interest in these meetups will grow and wane. Having one society that supports all of them should make starting or ending a meetup more straightforward and routine in the future.

> I also don't understand why this society should fund other meetups. I am not opposed I just don't understand it. If their is a valid reason I am all in.

See above.

**Comment by MarkBennett** [comment]
Just to be clear, I don't see one meetup sponsoring another meetup financially. The society would provide separate bank accounts (or equivalent) to keep the funds raised and spent by each meetup separate. The society would just take care of filling the financials etc.

**Comment by CAYdenberg** [comment]
Just to play devil's advocate, for fundraising purposes it might send a clearer message if the society is simply ExchangeJS, the money given goes to support ExchangeJS and the members are the meetup attendees (at whatever meetup we choose to have an AGM as a formality). 

I see the benefit in "one society, any meetup" structure (seems more DRY) but it might create some confusion when trying to petition for funds ("So the money is going to a JavaScript group?" "Well ...")

Just curious to know if you'd thought of it from that perspective?

As to your other points, electronic communication is preferable for me, too, and the other questions I don't have a strong opinion on.

**Comment by MarkBennett** [comment]
Good thinking @caydenberg. I'll reach out to Jibber and Clio, as well as a few other potential sponsors to see if this would be a concern.

**Comment by MarkBennett** [comment]
**UPDATE: To clarify, we probably won't record this whole process in the bylaws, just the minimum required to make voting via our issue tracker possible.**

In terms of voting, I'm proposing that we make online voting via our social issue tracker (read Github) the primary way we vote. Each vote would become an issue and would include in the issue description:

1) A description of the article being voted on
2) Links to any relevant documents or background material
3) A date by which members must vote
4) A record of how and when notice was given to members
5) Directions on whether to react to the issue or to specific comments

Members could then have the discussion and leave comments on the issue.

If the vote is a simple yes or no, then members would thumb up or down the issue to cast their vote. If the vote involves multiple options then a comment would be created for each option and members would thumb up the option they support. Thumbs down would be ignored in this case. When the vote closes a comment summarizing the votes and decision would be added and the issue would be closed.

When voting in person the secretary (or someone appointed to do this) would record all the votes in the issue tracker and they would be tallied as if they had voted online. A quorum that voted in person could also close the vote immediately.

Some outstanding issues I can see are:

1) What happens if the number of votes online doesn't add up to a quorum? Is the vote still binding?
2) Do we require 2-factor auth for voting members?
3) Any concerns with requiring members to have a Github account to vote?
4) What are reasonable minimum and maximum times to allow voting on an issue? I'd propose between 3-14 days at the discretion of the person creating the issue.

**Comment by MarkBennett** [comment]
I've heard back from a few sponsors now and can confirm that none I've spoken too (including Jobber and Clio) have an issue with the society using a different name.

/cc @caydenberg

**Comment by CAYdenberg** [comment]
FWIW, I don't think votes with multiple options are a good idea / allowed by Roger's Rules; a vote is to pass a particular motion or not.

If we allow a reasonable timeline to cast votes and everyone allowed to vote is notified (or should be notified) than I see no reason for a formal quorum. I think 7 days is reasonable and is fair given that everyone has different schedules.

**Comment by MarkBennett** [comment]
I didn't know that @CAYdenberg but it makes sense as I've only read about motions passing or not. It would make things simpler too so let's do that for now.

I'm in favour of not requiring quorum as it would also make things simpler, as long as everyone is comfortable with votes moving on without them after the required time.

**Comment by benzittlau** [comment]
One thing just to throw out there around the bylaws to consider is a "hijacking" of the org.  I've seen this happen in the wild, and while it'd be great if it's never an issue we have to contend with it's something to keep in mind.  Some of the measures you'd take to try and prevent that kind of takeover overlap with some bylaws/measures that seem overly burdensome (like requiring quorum).  For example, if the communication around pending votes isn't clear, someone could sneak through a ninja vote with a minority.  Not recommending any specific changes here, but it's important in the early stages of creating any org to plan not only for the good times, but for the bad times as well.

**Comment by MarkBennett** [comment]
Good tip @benzittlau. The draft bylaws I got from Matt certainly contemplate voting, notice, and quorum but I'll raise the specific issue of hijacking with him when I'm able.

I'm anticipating that the bylaws will be done by the end of June (hopefully sooner) then we can do that paperwork and incorporate immediately afterwards.

**Comment by MarkBennett** [comment]
Hi all,

If you haven't seen #76 yet, can you please leave any comments you've got on the bylaws by end of the week? I'll sit down with Matt and review them all after that.

https://docs.google.com/document/d/1i6oXabir-628csa2bQacHpc17Kmhec9EfkyHij9yQGM/edit?usp=sharing

Getting the bylaws finished is the last big step before we can get incorporated.

**Comment by MarkBennett** [comment]
Bylaws are complete (#76) as is the NUANS search (#78). I'm working on getting the paperwork done now, but we need to lock down the board members to wrap things up (#79).

As many of you have expressed interest in being on the board I've setup a form to sort through everyone:

https://docs.google.com/forms/d/e/1FAIpQLSd71TKKsnMpBn25GZvaiJQqcC0oypaJY_SJTL2S0AYUJrn32g/viewform?usp=sf_link

If you could fill this out by the end of the week we can make some decisions. It should only take a few minutes. Thanks!
